# Generated by Django 2.2.9 on 2020-02-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=200)),
                ('ingreso', models.FloatField(default=0.0)),
                ('gasto', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Dato',
                'verbose_name_plural': 'Datos',
                'ordering': ['-fecha'],
            },
        ),
    ]
